addons:
  # modules to install before running tests
  include:
    - contacts
    - stock

  # modules to exclude from installation/testing
  exclude:
    - hw_proxy
    - hw_escpos

  server_wide_modules:
    - web
